/**
 * MSG91 — SMS OTP + WhatsApp + Transactional SMS messaging
 *
 * Env vars required:
 *   MSG91_AUTH_KEY                  — MSG91 auth key
 *
 *   SMS OTP template IDs (DLT approved):
 *   MSG91_OTP_TEMPLATE_FORGOT       — forgot_password_otp_fwf_sms  (##name## ##otp## ##min##)
 *   MSG91_OTP_TEMPLATE_LOGIN        — login_otp_fwf_sms            (##name## ##otp## ##minutes##)
 *   MSG91_OTP_TEMPLATE_MEMBER       — Member mobile verification OTP
 *   MSG91_OTP_TEMPLATE_SUPPORTER    — Supporter mobile verification OTP
 *   MSG91_OTP_TEMPLATE_DONATION     — High-value donation OTP (≥₹50,000)
 *   MSG91_OTP_TEMPLATE_ID           — Fallback / generic OTP (backward-compat)
 *
 *   Transactional SMS template IDs (MSG91 Flow API):
 *   MSG91_SMS_QUIZ_PARTICIPATION    — Quiz_Participation_Confirmation_SMS  (##name## ##quizno##)
 *   MSG91_SMS_QUIZ_RESULT           — Quiz_Result_Announcement              (##name## ##quizno##)
 *   MSG91_SMS_DONATION_RECEIPT      — donation_receipt_sms                  (##name## ##amount##)
 *   MSG91_SMS_DONATION_80G          — donation_receipt_80g_sms              (##name## ##amount##)
 *
 *   MSG91_WA_NUMBER                 — Integrated WhatsApp business number (91XXXXXXXXXX)
 *   MSG91_WA_CREDENTIALS_TEMPLATE   — WhatsApp template name for welcome/credentials
 *   MSG91_WA_CREDENTIALS_SID        — Content SID for credentials template
 *   MSG91_WA_DONATION_TEMPLATE      — WhatsApp template name for donation confirmation
 *   MSG91_WA_DONATION_SID           — Content SID for donation template
 *
 * WhatsApp Template vars:
 *   Credentials: {{1}}=name, {{2}}=userId, {{3}}=password, {{4}}=loginUrl
 *   Donation:    {{1}}=name, {{2}}=amount, {{3}}=donationId, {{4}}=paymentId, {{5}}=date
 *
 * sendSmsOtp type values:
 *   'forgot'    — Forgot password OTP
 *   'login'     — Login OTP
 *   'member'    — Member mobile verification
 *   'supporter' — Supporter mobile verification
 *   'donation'  — High-value donation OTP
 */

const BASE_OTP  = 'https://control.msg91.com/api/v5/otp';
const BASE_FLOW = 'https://control.msg91.com/api/v5/flow/';
const BASE_WA   = 'https://api.msg91.com/api/v5/whatsapp/whatsapp-outbound-message/bulk/';

const authKey  = () => process.env.MSG91_AUTH_KEY || '';
const waNumber = () => process.env.MSG91_WA_NUMBER || '';

/** Format mobile to India format: 91XXXXXXXXXX */
function fmtMobile(mobile) {
  const digits = String(mobile).replace(/\D/g, '');
  return digits.startsWith('91') && digits.length === 12 ? digits : `91${digits.slice(-10)}`;
}

// ─── SMS OTP ─────────────────────────────────────────────────────────────────

/** Map OTP type → env var name */
const OTP_TEMPLATE_MAP = {
  forgot:    'MSG91_OTP_TEMPLATE_FORGOT',
  login:     'MSG91_OTP_TEMPLATE_LOGIN',
  member:    'MSG91_OTP_TEMPLATE_MEMBER',
  supporter: 'MSG91_OTP_TEMPLATE_SUPPORTER',
  donation:  'MSG91_OTP_TEMPLATE_DONATION',
};

/**
 * Send OTP via SMS.
 * Uses Twilio if TWILIO_ACCOUNT_SID is set (no DLT required),
 * otherwise falls back to MSG91 (requires DLT template).
 * @param {string} mobile  - recipient mobile
 * @param {string} otp     - 6-digit OTP (generated by caller)
 * @param {string} [type]  - 'forgot' | 'member' | 'supporter' | 'donation'
 */
export async function sendSmsOtp({ mobile, otp, type = 'donation' }) {
  // ── Twilio path (preferred — no DLT needed) ─────────────────────
  const twilioSid   = process.env.TWILIO_ACCOUNT_SID;
  const twilioToken = process.env.TWILIO_AUTH_TOKEN;
  const twilioFrom  = process.env.TWILIO_FROM_NUMBER;

  if (twilioSid && twilioToken && twilioFrom) {
    const typeLabels = {
      forgot:    'password reset',
      member:    'member verification',
      supporter: 'supporter verification',
      donation:  'donation verification',
    };
    const label = typeLabels[type] || 'verification';
    const body  = `${otp} is your FWF ${label} OTP. Valid for 10 minutes. Do not share. - FWF Livelihood Foundation`;
    try {
      const { default: twilio } = await import('twilio');
      const client = twilio(twilioSid, twilioToken);
      await client.messages.create({ body, from: twilioFrom, to: `+91${String(mobile).replace(/\D/g,'').slice(-10)}` });
      console.log(`✅ Twilio SMS OTP [${type}] sent → ${mobile}`);
      return { type: 'success' };
    } catch (e) {
      console.error('⚠️ Twilio SMS OTP failed:', e.message);
      return null;
    }
  }

  // ── MSG91 fallback (requires DLT template) ───────────────────────
  const key        = authKey();
  const envVar     = OTP_TEMPLATE_MAP[type] || 'MSG91_OTP_TEMPLATE_ID';
  const templateId = process.env[envVar] || process.env.MSG91_OTP_TEMPLATE_ID;
  if (!key || !templateId) {
    console.warn(`⚠️ SMS OTP skipped — set TWILIO_* or ${envVar}`);
    return null;
  }

  try {
    const res = await fetch(BASE_OTP, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'Authkey': key },
      body:    JSON.stringify({ template_id: templateId, mobile: fmtMobile(mobile), otp: String(otp) })
    });
    const data = await res.json();
    if (data.type === 'success') console.log(`✅ MSG91 SMS OTP sent → ${mobile}`);
    else console.error('⚠️ MSG91 SMS OTP error:', JSON.stringify(data));
    return data;
  } catch (e) {
    console.error('⚠️ MSG91 SMS OTP failed:', e.message);
    return null;
  }
}

// ─── WhatsApp ─────────────────────────────────────────────────────────────────

/** Internal: send a WhatsApp template message via MSG91 */
async function _sendWhatsApp({ mobile, templateName, contentSid, variables = [] }) {
  const key  = authKey();
  const from = waNumber();
  if (!key || !from) {
    console.warn('⚠️ MSG91 WhatsApp skipped — MSG91_AUTH_KEY or MSG91_WA_NUMBER not set');
    return null;
  }

  const components = variables.length
    ? [{ type: 'body', parameters: variables.map(v => ({ type: 'text', text: String(v) })) }]
    : [];

  const body = {
    integrated_number: from,
    content_sid:       contentSid || '',
    payload: {
      messaging_product: 'whatsapp',
      type:     'template',
      to:       fmtMobile(mobile),
      template: {
        name:       templateName,
        language:   { code: 'en' },
        components
      }
    }
  };

  try {
    const res  = await fetch(BASE_WA, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', 'Authkey': key },
      body:    JSON.stringify(body)
    });
    const data = await res.json();
    const ok = data.type === 'success' || String(data.message || '').toLowerCase().includes('success');
    if (ok) console.log(`✅ MSG91 WhatsApp [${templateName}] sent → ${mobile}`);
    else    console.error(`⚠️ MSG91 WhatsApp [${templateName}] error:`, JSON.stringify(data));
    return data;
  } catch (e) {
    console.error(`⚠️ MSG91 WhatsApp [${templateName}] failed:`, e.message);
    return null;
  }
}

/**
 * Send welcome WhatsApp with login credentials.
 * Template vars: {{1}}=name  {{2}}=userId  {{3}}=password  {{4}}=loginUrl
 */
export async function sendWhatsAppCredentials({ mobile, name, userId, password }) {
  if (!mobile) return null;
  return _sendWhatsApp({
    mobile,
    templateName: process.env.MSG91_WA_CREDENTIALS_TEMPLATE || 'fwf_welcome_credentials',
    contentSid:   process.env.MSG91_WA_CREDENTIALS_SID   || '',
    variables: [
      name,
      userId,
      password,
      'https://www.fwfindia.org/member-login.html'
    ]
  });
}

/**
 * Send WhatsApp donation confirmation.
 * Template vars: {{1}}=name  {{2}}=amount  {{3}}=donationId  {{4}}=paymentId  {{5}}=date
 */
export async function sendWhatsAppDonation({ mobile, name, amount, donationId, paymentId }) {
  if (!mobile) return null;
  const formatted = Number(amount).toLocaleString('en-IN');
  const date      = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
  return _sendWhatsApp({
    mobile,
    templateName: process.env.MSG91_WA_DONATION_TEMPLATE || 'fwf_donation_confirmation',
    contentSid:   process.env.MSG91_WA_DONATION_SID   || '',
    variables: [name, `Rs. ${formatted}`, donationId, paymentId, date]
  });
}

// ─── Transactional SMS (Flow API) ────────────────────────────────────────────

/** Internal: send transactional SMS via MSG91 Flow API using an approved DLT template */
async function sendTransactionalSms({ mobile, templateId, variables = {} }) {
  const key = authKey();
  if (!key || !templateId) {
    console.warn('⚠️ Transactional SMS skipped — MSG91_AUTH_KEY or template ID not set');
    return null;
  }
  const recipient = { mobiles: fmtMobile(mobile), ...variables };
  try {
    const res = await fetch(BASE_FLOW, {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', authkey: key },
      body:    JSON.stringify({ template_id: templateId, short_url: 0, realTimeResponse: 1, recipients: [recipient] })
    });
    const data = await res.json();
    const ok = data.type === 'success' || String(data.message || '').toLowerCase().includes('success');
    if (ok) console.log(`✅ MSG91 SMS [${templateId.slice(-6)}] sent → ${mobile}`);
    else    console.error(`⚠️ MSG91 SMS [${templateId.slice(-6)}] error:`, JSON.stringify(data));
    return data;
  } catch (e) {
    console.error(`⚠️ MSG91 SMS failed:`, e.message);
    return null;
  }
}

/**
 * Send quiz participation confirmation SMS.
 * Template: Quiz_Participation_Confirmation_SMS
 * Vars: ##name## ##quizno##
 */
export async function sendQuizParticipationSms({ mobile, name, quizId }) {
  if (!mobile) return null;
  return sendTransactionalSms({
    mobile,
    templateId: process.env.MSG91_SMS_QUIZ_PARTICIPATION,
    variables:  { name, quizno: quizId }
  });
}

/**
 * Send quiz result announcement SMS.
 * Template: Quiz_Result_Announcement
 * Vars: ##name## ##quizno##
 */
export async function sendQuizResultSms({ mobile, name, quizId }) {
  if (!mobile) return null;
  return sendTransactionalSms({
    mobile,
    templateId: process.env.MSG91_SMS_QUIZ_RESULT,
    variables:  { name, quizno: quizId }
  });
}

/**
 * Send donation receipt SMS.
 * Template: donation_receipt_sms
 * Vars: ##name## ##amount##
 */
export async function sendDonationReceiptSms({ mobile, name, amount }) {
  if (!mobile) return null;
  return sendTransactionalSms({
    mobile,
    templateId: process.env.MSG91_SMS_DONATION_RECEIPT,
    variables:  { name, amount: `${Number(amount).toLocaleString('en-IN')}` }
  });
}

/**
 * Send 80G donation receipt SMS.
 * Template: donation_receipt_80g_sms
 * Vars: ##name## ##amount##
 */
export async function sendDonationReceipt80GSms({ mobile, name, amount }) {
  if (!mobile) return null;
  return sendTransactionalSms({
    mobile,
    templateId: process.env.MSG91_SMS_DONATION_80G,
    variables:  { name, amount: `${Number(amount).toLocaleString('en-IN')}` }
  });
}
